In [82]:
import pandas as pd
import numpy as np
df=pd.read_csv('Data_Salaries.csv')

df.tail()

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,company_location,company_size
3756,2020,SE,FT,Principal_Data_Scientist,130000.0,EUR,148261.0,DE,M
3757,2020,SE,FT,Data_Scientist,80000.0,EUR,91237.0,AT,S
3758,2020,SE,FT,Data_Science_Manager,190200.0,USD,190200.0,US,M
3759,2020,SE,FT,Machine_Learning_Engineer,40000.0,EUR,45618.0,HR,S
3760,2020,SE,FT,Data_Scientist,412000.0,USD,412000.0,US,L

In [83]:
df.describe()

         work_year        salary  salary_in_usd
count  3761.000000  3.757000e+03    3757.000000
mean   2022.374103  1.906490e+05  137579.469257
std       0.691252  6.715006e+05   63030.664657
min    2020.000000  6.000000e+03    5132.000000
25%    2022.000000  1.000000e+05   95000.000000
50%    2022.000000  1.375000e+05  135000.000000
75%    2023.000000  1.800000e+05  175000.000000
max    2023.000000  3.040000e+07  450000.000000

In [84]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3761 entries, 0 to 3760
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   work_year         3761 non-null   int64
 1   experience_level  3757 non-null   object
 2   employment_type   3760 non-null   object
 3   job_title         3751 non-null   object
 4   salary            3757 non-null   float64
 5   salary_currency   3752 non-null   object
 6   salary_in_usd     3757 non-null   float64
 7   company_location  3759 non-null   object
 8   company_size      3760 non-null   object
dtypes: float64(2), int64(1), object(6)
memory usage: 264.6+ KB

In [85]:
df.columns #gives columns names ordered

Index(['work_year', 'experience_level', 'employment_type', 'job_title',
       'salary', 'salary_currency', 'salary_in_usd', 'company_location',
       'company_size'],
      dtype='object')

In [86]:
df.shape #better than df.size bcs it gives nymber of lines and columns

(3761, 9)

In [87]:
mv=df.isnull().sum()
mv

work_year            0
experience_level     4
employment_type      1
job_title           10
salary               4
salary_currency      9
salary_in_usd        4
company_location     2
company_size         1
dtype: int64

In [88]:
sum(df.isnull().sum()) #somme totale des valeurs nulles

35

You can fill null values with:
mode: when data is categorical
mean & median: numerical

In [89]:
categorical_col=df.select_dtypes(exclude=np.number).columns #check the notes on the function to know the parameters
categorical_col

Index(['experience_level', 'employment_type', 'job_title', 'salary_currency',
       'company_location', 'company_size'],
      dtype='object')

In [90]:
categorical_cols=df.select_dtypes(include=object).columns #check the notes on the function to know the parameters
categorical_cols

Index(['experience_level', 'employment_type', 'job_title', 'salary_currency',
       'company_location', 'company_size'],
      dtype='object')

In [91]:
numerical_col=df.select_dtypes(include=np.number).columns #or number instead of np.number
numerical_col

Index(['work_year', 'salary', 'salary_in_usd'], dtype='object')

## Filling missing values

### Methods for filling NaaN (Impute):
- Mean/Median for numerical columns
- Mode for categorical columns
- Least occured value ≠ Mode for categorical columns
- bfill(), ffill() from pandas;  bfill : backward-filling;  ffill : forward-filling (classic methods)

- sklearn.impute: IterativeImputer, KNNImputer, MissingIndicator, SimpleImputer (more advanced methods)
- feature engine: Random Imputation, CategoricalImputer

- Listewise/Pairwise deletion (more complex in particual cases )

In [92]:
mv 
#mv is just a snapshot of the missing values at that moment. It doesn't dynamically update after you modify the DataFrame.

work_year            0
experience_level     4
employment_type      1
job_title           10
salary               4
salary_currency      9
salary_in_usd        4
company_location     2
company_size         1
dtype: int64

In [93]:
df['job_title']=df['job_title'].fillna(df['job_title'].mode()[0])
#Rks: mode() displays index and mode, so we write mode()[0] to get the mode only
#i can use inplace=True, in that case no need to create a new variable and assign the function to it. We apply the fucntion directly and it changes the orginal data
#what we did: Create a new Series and assigns it back to df['salary'].

In [94]:
df['job_title'].mode()

0    Data_Engineer
Name: job_title, dtype: object

In [95]:
type(df['job_title'].mode()) #the type of mode function is series like array or dataframe so to slice we need []

pandas.core.series.Series

In [96]:
#to chack if there is a change
df.isnull().sum()

work_year           0
experience_level    4
employment_type     1
job_title           0
salary              4
salary_currency     9
salary_in_usd       4
company_location    2
company_size        1
dtype: int64

In [97]:
df['salary'].mean()

np.float64(190648.9853606601)

In [98]:
df['salary']=df['salary'].fillna(df['salary'].mean())

In [99]:
df['salary_in_usd']=df['salary_in_usd'].fillna(df['salary_in_usd'].mean())

In [100]:
df.isnull().sum()

work_year           0
experience_level    4
employment_type     1
job_title           0
salary              0
salary_currency     9
salary_in_usd       0
company_location    2
company_size        1
dtype: int64

In [101]:
df['salary_currency'].value_counts() #occurences, type is series (it displays name and dtype)
#value_counts returns series. Then USD, etc are index and in front of them are the values

salary_currency
USD    3220
EUR     236
GBP     162
INR      60
CAD      25
AUD       9
SGD       6
BRL       6
PLN       5
CHF       4
DKK       3
HUF       3
TRY       3
JPY       3
THB       2
HKD       1
CZK       1
ILS       1
CLP       1
MXN       1
Name: count, dtype: int64

In [102]:
least_occurred_value=df['salary_currency'].value_counts().idxmin() #idxmin and idxmax show least and most occured values
least_occurred_value

'HKD'

In [103]:
df['salary_currency']=df['salary_currency'].fillna(least_occurred_value) #we can fill missing values with 0 (in numerical cols)

In [104]:
df.isnull().sum()

work_year           0
experience_level    4
employment_type     1
job_title           0
salary              0
salary_currency     0
salary_in_usd       0
company_location    2
company_size        1
dtype: int64

In [105]:
df['experience_level']=df['experience_level'].fillna('N/A')

In [106]:
df.isnull().sum()

work_year           0
experience_level    0
employment_type     1
job_title           0
salary              0
salary_currency     0
salary_in_usd       0
company_location    2
company_size        1
dtype: int64

In [107]:
for col in ['employment_type','company_location','company_size']:
    df[col]=df[col].fillna(df[col].bfill())

In [108]:
sum(df.isnull().sum())

0

## Apply(), Aggregation() & GroupBy()

In [109]:
df['experience_level'].value_counts()

experience_level
SE     2516
MI      807
EN      320
EX      114
N/A       4
Name: count, dtype: int64

In [112]:
df['experience_level']=df['experience_level'].apply(lambda x:x.lower( )) #apply lambda modifies the cells of the column.
#lower can be replaced by upper(), title().. string functions

In [113]:
df['experience_level'].value_counts()

experience_level
se     2516
mi      807
en      320
ex      114
n/a       4
Name: count, dtype: int64

In [115]:
df['job_title'].value_counts()

job_title
Data_Engineer                1048
Data_Scientist                839
Data_Analyst                  609
Machine_Learning_Engineer     289
Analytics_Engineer            103
                             ...
Marketing_Data_Engineer         1
Cloud_Data_Architect            1
Staff_Data_Scientist            1
Finance_Data_Analyst            1
Staff_Data_Analyst              1
Name: count, Length: 93, dtype: int64

In [116]:
df.groupby(by=['job_title'])['salary'].mean()

job_title
3D_Computer_Vision_Researcher    120000.000000
AI_Developer                     137181.818182
AI_Programmer                     55000.000000
AI_Scientist                     275312.500000
Analytics_Engineer               151352.621359
                                     ...
Research_Engineer                162752.810811
Research_Scientist               160768.890244
Software_Data_Engineer            75000.000000
Staff_Data_Analyst                15000.000000
Staff_Data_Scientist             105000.000000
Name: salary, Length: 93, dtype: float64

In [117]:
df.groupby(by=['job_title'])['salary'].mean().idxmax()

'Head_of_Machine_Learning'